AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Lambda function for monitoring CPU and network usage metrics of EC2 instances across multiple regions and sending monthly summaries via SNS.

Parameters:
  ScheduleExpression:
    Description: Cron expression for the schedule
    Type: String
    Default: cron(0 0 1 * ? *)
  ParentAlertStack:
    Description: The name of the parent stack that exports the SNS topic ARN
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Parent Stacks'
        Parameters:
          - ParentAlertStack

Resources:
  ec2cpunetworkfunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.9
      Timeout: 300
      MemorySize: 512
      Code:
        ZipFile: |
          import boto3
          import datetime
          import os
          
          def lambda_handler(event, context):
              # Initialize STS and SNS clients
              sts_client = boto3.client('sts')
              sns_client = boto3.client('sns')
          
              # Get AWS account ID and region of the Lambda function
              account_id = sts_client.get_caller_identity()["Account"]
              lambda_region = boto3.session.Session().region_name
          
              # Get a list of all regions
              ec2 = boto3.client('ec2', region_name=lambda_region)
              regions = [region['RegionName'] for region in ec2.describe_regions()['Regions']]
          
              # Initialize message
              message = f"AWS Account ID: {account_id}, Lambda Function Region: {lambda_region}\n"
          
              # Iterate over all regions and process instances
              for region in regions:
                  region_message_added = False
          
                  ec2_client = boto3.client('ec2', region_name=region)
                  cloudwatch_client = boto3.client('cloudwatch', region_name=region)
          
                  instances = ec2_client.describe_instances()
                  instance_ids = [instance['InstanceId'] for reservation in instances['Reservations'] for instance in reservation['Instances']]
          
                  for instance_id in instance_ids:
                      instance_message = process_instance(instance_id, cloudwatch_client)
          
                      if instance_message:
                          if not region_message_added:
                              message += f"Region: {region}\n"
                              region_message_added = True
                          message += instance_message
          
              # Send one notification with all data
             #sns_client.publish(TopicArn='TOPIC_ARN', Message=message)
              sns_client.publish(TopicArn=os.environ['TOPIC_ARN'], Message=message)
              
          def process_instance(instance_id, cloudwatch_client):
              # Define timestamps for current and previous month
              now = datetime.datetime.now()
              start_current_month = datetime.datetime(now.year, now.month, 1, 0, 0, 0)
              end_current_month = datetime.datetime(now.year, now.month, now.day, 23, 59, 59)
          
              # Calculate the first and last day of the previous month
              first_day_prev_month = start_current_month - datetime.timedelta(days=1)
              start_prev_month = datetime.datetime(first_day_prev_month.year, first_day_prev_month.month, 1, 0, 0, 0)
              end_prev_month = datetime.datetime(first_day_prev_month.year, first_day_prev_month.month, first_day_prev_month.day, 23, 59, 59)
          
              # Format timestamps
              current_month_timestamp = end_current_month.strftime('%d/%m/%Y')
              previous_month_timestamp = end_prev_month.strftime('%d/%m/%Y')
          
              # Fetch metrics for current and previous month
              current_cpu_data = get_metric_statistics(cloudwatch_client, instance_id, start_current_month, end_current_month, 'CPUUtilization', 'Average')
              previous_cpu_data = get_metric_statistics(cloudwatch_client, instance_id, start_prev_month, end_prev_month, 'CPUUtilization', 'Average')
              current_net_out_data = get_metric_statistics(cloudwatch_client, instance_id, start_current_month, end_current_month, 'NetworkOut', 'Sum')
              previous_net_out_data = get_metric_statistics(cloudwatch_client, instance_id, start_prev_month, end_prev_month, 'NetworkOut', 'Sum')
              current_net_in_data = get_metric_statistics(cloudwatch_client, instance_id, start_current_month, end_current_month, 'NetworkIn', 'Sum')
              previous_net_in_data = get_metric_statistics(cloudwatch_client, instance_id, start_prev_month, end_prev_month, 'NetworkIn', 'Sum')
              current_status_check_failed = get_metric_statistics(cloudwatch_client, instance_id, start_current_month, end_current_month, 'StatusCheckFailed', 'Average')
              previous_status_check_failed = get_metric_statistics(cloudwatch_client, instance_id, start_prev_month, end_prev_month, 'StatusCheckFailed', 'Average')
          
              # Calculate CPU averages and convert Network data to GB
              current_avg_cpu = format(calculate_average(current_cpu_data), '.2f') + '%'
              previous_avg_cpu = format(calculate_average(previous_cpu_data), '.2f') + '%'
              current_net_out = format(sum_datapoints(current_net_out_data) / 1073741824, '.3f') + ' GB'
              previous_net_out = format(sum_datapoints(previous_net_out_data) / 1073741824, '.3f') + ' GB'
              current_net_in = format(sum_datapoints(current_net_in_data) / 1073741824, '.3f') + ' GB'
              previous_net_in = format(sum_datapoints(previous_net_in_data) / 1073741824, '.3f') + ' GB'
              current_status_check = format(calculate_average(current_status_check_failed), '.2f')
              previous_status_check = format(calculate_average(previous_status_check_failed), '.2f')
          
              # Build the message for the instance
              return f"Instance ID: {instance_id}\n" \
                     f"    - Current Month (End: {current_month_timestamp})\n" \
                     f"        CPU: {current_avg_cpu}, Network Out: {current_net_out}, Network In: {current_net_in}, Status Check Failed (Avg): {current_status_check}\n" \
                     f"    - Previous Month (End: {previous_month_timestamp})\n" \
                     f"        CPU: {previous_avg_cpu}, Network Out: {previous_net_out}, Network In: {previous_net_in}, Status Check Failed (Avg): {previous_status_check}\n\n"
              
          
          def get_metric_statistics(cloudwatch_client, instance_id, start, end, metric_name, statistic):
              response = cloudwatch_client.get_metric_statistics(
                  Namespace='AWS/EC2',
                  MetricName=metric_name,
                  Dimensions=[
                      {
                          'Name': 'InstanceId',
                          'Value': instance_id
                      },
                  ],
                  StartTime=start,
                  EndTime=end,
                  Period=3600,
                  Statistics=[statistic]
              )
              return response['Datapoints']
          
          def calculate_average(metric_data):
              if not metric_data:
                  return 0
              total = sum(datapoint['Average'] for datapoint in metric_data)
              average = total / len(metric_data)
              return average
          
          def sum_datapoints(metric_data):
              return sum(datapoint['Sum'] for datapoint in metric_data if 'Sum' in datapoint)          
      Environment:
        Variables:
          TOPIC_ARN: {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Tags:
        - Key: 'Name'
          Value: !Ref 'AWS::StackName'

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - cloudwatch:GetMetricStatistics
                  - ec2:DescribeRegions
                  - sns:Publish
                Resource: '*'
      Tags:
        - Key: 'Name'
          Value: !Ref 'AWS::StackName'

  ec2cpunetworkMonthlyTrigger:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref 'AWS::StackName'
      ScheduleExpression: !Ref ScheduleExpression
      Targets:
        - Arn: !GetAtt ec2cpunetworkfunction.Arn
          Id: MonthlyLambdaTrigger
      State: ENABLED

  LambdaPermissionForEventsToInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ec2cpunetworkfunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ec2cpunetworkMonthlyTrigger.Arn

Outputs:
  LambdaFunctionARN:
    Description: The ARN of the Lambda function
    Value: !GetAtt ec2cpunetworkfunction.Arn
